module.exports = {
  "widgets": {
    "downloader": {
      "defaultButtonText": "下载",
      "msgFileTypeError": "无效的文件类型"
    },
    "banner": {
      "thirdText": "第三方",
      "qcSystemText": "质控平台",
      "currentUserText": "登录用户",
      "userProfileText": "用户信息",
      "logOffText": "退出"
    },
    "datagrid": {
      "noRecordsText": "没有匹配的记录",
      "goToText": "跳转",
      "pageSizeText": "每页显示(行)"
    },
    "filter": {
      "inputKeywordText": "输入关键字"
    },
    "history": {
      "backText": "返回"
    },
    "buttonGroup": {
      "deleteText": "删除",
      "saveText": "保存",
      "cancelText": "取消"
    },
    "menu": {
      "searchModuleText": "搜索功能",
    },
    "wizard": {
      "nextButtonText": "下一步",
      "prevButtonText": "上一步",
      "finishButtonText": "完成",
      "cancelButtonText": "取消",
      "okButtonText": "确定"
    }
  },
  "forms": {
    "expectOptions": {
      "scoreWeightText": "分值",
      "inputScoreWeightText": "请输入分值",
      "addText": "添加",
      "optionValueText": "选项值",
      "optionText": "选项",
      "targetValue": "靶值",
      "inputOptionText": "请输入选项",
      "okButtonText": "确定",
      "upOffsetText": "上偏移",
      "downOffsetText": "下偏移",
      "averageValueText": "平均数",
      "standardDValueText": "标准差",
      "customizeText": "已设置",
      "nonCustomizeText": "未设置",
      "qualitativeText": "定性",
      "quantitativeText": "定量",
      "gaussianDistributionText": "正态分布"
    },
    "header": {
      "inputHeaderText": "请输入标题"
    },
    "footer": {
      "inputStatementText": "输入说明内容"
    },
    "group": {
      "categoryText": "检测分类",
      "specimenText": "样本",
      "scoreText": "分数",
      "codeText": "代码",
      "codeGroupText": "代码组",
      "batchCodeText": "试剂批号",
      "expireDateText": "有效期",
      "inputBatchCodeText": "输入试剂批号",
      "inputExpireDateText": "输入有效期",
      "inputTesterText": "输入检测人",
      "inputReviewerText": "输入审核人",
      "testerText": "检测人",
      "reviewerText": "审核人",
      "inputTestDateText": "请输入检测日期",
      "inputReviewDateText": "请输入审核日期",
      "testDateText": "检测日期",
      "reviewDateText": "审核日期",
      "getText": "得",
      "commentText": "备注",
      "statementText": "填报说明",
      "nameText": "名称",
      "inputGroupNameText": "输入分组名",
      "addGroupText": "添加分组",
      "addSpecimenText": "添加样本",
      "addCodeGroupText": "添加代码组",
      "addTestItemText": "添加新项目",
      "inputSpecimenNumberText": "请输入样本编号",
      "mixedSpecimenNumberText": "样本组成",
      "addMixedSpecimenNumberText": "添加混合样本号",
      "copyFromExistingSpecimenText": "从其他样本复制",
      "okButtonText": "确定",
      "testItemText": "检测项",
      "disableCodeGroupText": "禁用代码组",
      "msgInvalidSpecimenError": "无效的样本编号",
      "msgDuplicatedSpecimenError": "请勿重复输入"
    }
  },
  "controls": {
    "checkbox": {
      "valueY": "是",
      "valueN": "否"
    }
  },
  "charts": {

  },
  "pages": {
    "common": {
      "statusText": "状态",
      "statusActiveText": "有效",
      "statusInactiveText": "无效",
      "msgSaveCompleted": "保存成功",
      "msgConfirmDelete": "删除操作无法恢复,是否确定要删除?",
      "okText": "确定",
      "backText": "返回",
      "cancelText": "取消"
    },
    "assessmentTemplate": {
      "nameText": "名称",
      "newText": "新建",
      "openText": "打开",
      "saveText": "保存",
      "copyText": "复制",
      "deleteText": "删除",
      "designViewText": "设计视图",
      "addTestGroupText": "添加检测分组",
      "deleteTestGroupText": "删除检测分组",
      "statementText": "填报说明",
      "okButtonText": "确定",
      "cancelButtonText": "取消",
      "msgSaveSuccessText": "保存成功",
      "msgDeleteConfirmText": "删除操作无法恢复,是否确定要删除?",
      "msgDeleteSuccessText": "删除成功"
    },
    "users": {
      "createUserText": "创建新用户",
      "usernameText": "用户名",
      "inputUsernameText": "请输入用户名",
      "passwordText": "密码",
      "inputPasswordText": "请输入密码",
      "confirmPasswordText": "确认密码",
      "inputConfirmPasswordText": "请再次输入密码",
      "nameText": "姓名",
      "inputNameText": "请输入姓名",
      "phoneText": "电话",
      "inputPhoneText": "请输入电话",
      "roleText": "角色",
      "orgText": "卫生机构",
      "orgUserText": "卫生机构用户",
      "orgNameText": "所属卫生机构",
      "supervisorText": "上级单位",
      "msgInvalidUsernameError": "请输入有效用户名(长度3到8位的字符)",
      "msgInvalidNameError": "姓名不能为空",
      "msgInvalidPasswordError": "请输入有效密码(长度6到10位的字符)",
      "msgInvalidPasswordNotMatchError": "两次密码不一致"
    },
    "forms": {
      "submitText": "提交",
      "formText": "表单",
      "previewText": "预览",
      "uploadAttachmentText": "上传附件",
      "msgSubmitConfirm": "答案一旦提交无法修改,是否确定提交?",
      "msgAttachmentWarning": "注意: 每个表单只能上传一个附件，重复上传会相互覆盖.且文件大小不能大于50MB",
      "chooseFileText": "选择文件",
      "viewAttachmentText": "查看附件",
      "assessmentOwnerText": "考评发起单位",
      "submitDate": "提交日期",
      "scoreText": "分数",
      "totalScoreText": "总分",
      "attachmentScoreText": "附加分",
      "actionText": "操作",
      "uploadText": "上传",
      "msgSaved": "保存成功",
      "msgUploaded": "上传成功",
      "msgFailed": "上传失败",
      "msgChooseFile": "请选择文件"
    },
    "participants": {
      "orgNameText": "名称",
      "msgOrgRequiredNameError": "名称不能为空",
      "provinceText": "省份",
      "cityText": "城市",
      "districtText": "地区",
      "postcodeText": "邮编",
      "qualificationText": "机构资质",
      "orgTypeText": "机构类型",
      "iconText": "图标(不超过5M)",
      "signatureText": "公章(不超过5M,尺寸200x200,PNG格式)",
      "userListText": "用户列表",
      "affiliatesText": "下属单位",
      "addAffiliatesText": "添加机构",
      "supervisorText": "上级",
      "qualification1": "一级",
      "qualification2": "二级",
      "qualification3": "三级",
      "uploadCompleteText": "上传成功",
      "uploadFailedText": "上传失败",
      "deleteText": "删除",
      "createOrgText": "创建卫生医疗单位",
      "inputOrgNameText": "请输入名称",
      "inputProvinceText": "请输入省份",
      "inputCityText": "请输入城市",
      "inputDistrictText": "请输入地区",
      "inputPostcodeText": "请输入邮编",
      "inputAddressText": "请输入地址",
      "addressText": "地址",
      "inputOrgTypeText": "输入机构性质",
      "noAffiliatesText": "尚无下属机构"
    },
    "roles": {
      "createRoleText": "创建新角色",
      "moduleText": "模块",
      "functionalityText": "功能",
      "readText": "查看",
      "saveText": "修改",
      "addText": "添加",
      "deleteText": "删除",
      "roleNameText": "角色名称",
      "msgRequireRoleNameError": "角色名不能为空",
      "inputRoleNameText": "输入角色名"
    },
    "categories": {
      "createCategoryText": "创建检测类别",
      "categoryNameText": "名称",
      "inputCategoryNameText": "请输入检测类别名称",
      "msgRequireCategoryNameError": "检测类别名称不能为空"
    },
    "codeGroups": {
      "createCodeGroupText": "创建代码组",
      "groupNameText": "名称",
      "inputGroupNameText": "请输入代码组名称",
      "msgRequireNameError": "代码组名称不能为空"
    },
    "codes": {
      "createCodeText": "创建代码",
      "codeText": "代码编号",
      "codeNameText": "类别名称",
      "inputCodeText": "请输入代码编号",
      "inputCodeNameText": "请输入类别名称",
      "msgRequireCodeError": "代码编号不能为空",
      "msgRequireCodeNameError": "类别名称不能为空",
      "codeGroupText": "代码组",
      "testCategoryText": "检测类别",
      "addCategoryText": "增加类别",
      "categoryText": "类别",
      "actionText": "操作"
    },
    "assessment": {
      "msgNewAssessmentConfirmText": "考评提交后将无法修改,请仔细核实提交的数据.是否确定提交?",
      "msgRequireTemplateError": "没有选择测试模版",
      "msgRequireAllCertFieldsError": "证书字段不能为空",
      "msgInvalidScoreError": "请输入合法的合格分数",
      "msgRequireAllFields": "所有字段必须填写",
      "msgRequireParticipantError": "至少选择一个参与单位",
      "msgRequireSpecimenCodeError": "请输入盲样码",
      "assessmentNameText": "考评名称",
      "inputAssessmentNameText": "输入考评名称",
      "templateText": "模版",
      "startDateText": "开始日期",
      "endDateText": "结束日期",
      "enableCertificationText": "启用证书",
      "qualificationScoreText": "合格分数",
      "inputQualificationScoreText": "输入合格分数",
      "issuerText": "颁发者",
      "inputIssuerText": "输入颁发者名称",
      "issueDateText": "颁发日期",
      "certTitleText":"证书标题",
      "inputCertTitleText":"输入证书标题",
      "certSubTitleText":"证书子标题",
      "inputCertSubTitleText":"输入证书子标题",
      "certContentText":"证书内容",
      "inputCertContentText":"输入证书内容",
      "certCommentLabelText":"证书备注标题",
      "inputCertCommentLabelText":"输入证书备注标题",
      "certCommentText":"证书备注",
      "inputCertCommentText":"输入证书备注",
      "previewCertText": "预览证书",
      "selectParticipantsText": "请选择考评机构",
      "specimenText": "样本",
      "inputSpecimenCodeText": "设置盲样码",
      "actionText": "操作",
      "okButtonText": "确定",
      "cancelButtonText": "取消",
      "singleSpecimenCodeText": "单盲样码",
      "doubleSpecimenCodeText": "双盲样码",
      "participantText": "机构",
      "creatorText": "创建人",
      "statusText": "状态",
      "addParticipantText": "添加机构",
      "assessmentScoreText": "考评得分",
      "additionalScoreText": "附加分",
      "totalScoreText": "总分",
      "exportText": "导出",
      "deleteText": "删除",
      "reopenText": "重开",
      "rejectText": "打回",
      "attachmentText": "附件",
      "finalizeText": "结束",
      "statusUnknownText": "未知状态",
      "statusFinalizedText": "已完成",
      "statusInprogressText": "进行中",
      "statusReviewedText": "已审核",
      "statusUnfilledText": "未完成",
      "statusDraftText": "草稿",
      "statusReviewingText": "评审中",
      "statusPublishedText": "已发布",
      "statusFilledText": "已提交",
      "certificationText": "证书",
      "supervisorText": "上级",
      "assessmentsText": "考评记录",
      "testCategoryText": "检测分类",
      "msgConfirmReopen": "是否确定打回操作?",
      "msgConfirmReset": "是否确定要重置考评?",
      "msgConfirmDeleteAssessment": "删除操作会清空所有本次考评的提交结果,是否确定要删除?",
      "msgOperationComplete": "操作成功",
      "msgConfirmDelete": "是否确定删除操作?",
      "additionScoreStatementText": "说明",
      "inputAdditionScoreStatementText": "请输入附加分说明",
      "msgConfirmFinalize": "考评提交后将不能修改,请检查确定无误后提交?",
      "averageText": "均值"
    }
  }
};