module.exports = {
  "widgets": {
    "downloader": {
      "defaultButtonText": "Download",
      "msgFileTypeError": "Invalid file type"
    },
    "banner": {
      "thirdText": "The Third",
      "qcSystemText": "QC System",
      "currentUserText": "Account",
      "userProfileText": "Profile",
      "logOffText": "Log off"
    },
    "datagrid": {
      "noRecordsText": "No records",
      "goToText": "Go to",
      "pageSizeText": "Page size"
    },
    "filter": {
      "inputKeywordText": "Search with keyword"
    },
    "history": {
      "backText": "Back"
    },
    "buttonGroup": {
      "deleteText": "Delete",
      "saveText": "Save",
      "cancelText": "Cancel"
    },
    "menu": {
      "searchModuleText": "Search",
    },
    "wizard": {
      "nextButtonText": "Next",
      "prevButtonText": "Back",
      "finishButtonText": "Finish",
      "cancelButtonText": "Cancel",
      "okButtonText": "OK"
    }
  },
  "forms": {
    "notice": {
      "assetsText": "Assets",
      "assetsManagementText": "Manage Assets",
      "announcementText": "Announcement",
      "announcementManagementsText": "Manage Announcements",
      "titleText": "Title",
      "dateText": "Publish Date",
      "authorText": "Author",
      "placeholderText": "Enter your content here",
      "inputTitleText": "Please input notice title",
      "addNewButtonText": "Add New",
      "msgSaveSuccessfullyText": "Save successfully",
      "msgConfirmDeleteText": "Are you sure to remove?",
      "downloadText": "Download",
      "copyToClipboardText": "Copy Url to Clipboard",
      "deleteText": "Delete",
      "msgCopySuccessfullyText": "Asset url has been copied to clipboard",
      "msgUploadingInProgressText": "Uploading is in progress, you need to wait until uploading finish",
      "markAsUnReadText": "Mark as unread",
      "markAsReadText": "Mark as read"
    },
    "expectOptions": {
      "scoreWeightText": "Score weight",
      "inputScoreWeightText": "Please input score weight",
      "addText": "Add",
      "optionValueText": "Option value",
      "optionText": "Option",
      "targetValue": "Target value",
      "inputOptionText": "Please input option",
      "okButtonText": "OK",
      "upOffsetText": "Up offset",
      "downOffsetText": "Down offset",
      "averageValueText": "Average",
      "standardDValueText": "Standard D-Value",
      "customizeText": "Set",
      "nonCustomizeText": "Set",
      "qualitativeText": "Qualitative",
      "quantitativeText": "Quantitative",
      "gaussianDistributionText": "Gaussian distribution"
    },
    "header": {
      "inputHeaderText": "Please input header"
    },
    "footer": {
      "inputStatementText": "Please input statement"
    },
    "group": {
      "categoryText": "Category",
      "specimenText": "Specimen",
      "scoreText": "Score",
      "codeText": "Code",
      "codeGroupText": "Code Group",
      "batchCodeText": "Batch code",
      "expireDateText": "Expire date",
      "inputBatchCodeText": "Please input batch code",
      "inputExpireDateText": "Please input expire date",
      "inputTesterText": "Please input tester name",
      "inputReviewerText": "Please input reviewer name",
      "testerText": "Tester",
      "reviewerText": "Reviewer",
      "inputTestDateText": "Please input test date",
      "inputReviewDateText": "Please input review date",
      "testDateText": "Test Date",
      "reviewDateText": "Review Date",
      "getText": "get",
      "commentText": "Comment",
      "statementText": "Notes",
      "nameText": "Name",
      "inputGroupNameText": "Test group name",
      "addGroupText": "Add group",
      "addSpecimenText": "Add specimen",
      "addCodeGroupText": "Add code group",
      "addTestItemText": "Add test item",
      "inputSpecimenNumberText": "Please input specimen number",
      "mixedSpecimenNumberText": "Mixed specimen",
      "addMixedSpecimenNumberText": "Add mixed specimen",
      "duplicatedOrInvalidGuidText": "Invalid Or Duplicated Specimen",
      "copyFromExistingSpecimenText": "Copy from existing specimen",
      "okButtonText": "OK",
      "testItemText": "Test item",
      "disableCodeGroupText": "Disable code group",
      "msgInvalidSpecimenError": "Invalid specimen number",
      "msgDuplicatedSpecimenError": "Specimen number already exists"
    }
  },
  "controls": {
    "checkbox": {
      "valueY": "Yes",
      "valueN": "No"
    }
  },
  "charts": {

  },
  "pages": {
    "common": {
      "statusText": "Status",
      "statusActiveText": "Active",
      "statusInactiveText": "Inactive",
      "msgSaveCompleted": "Save Complete",
      "msgConfirmDelete": "You are sure to delete record",
      "okText": "OK",
      "backText": "Back",
      "cancelText": "Cancel"
    },
    "assessmentTemplate": {
      "nameText": "Name",
      "newText": "New",
      "openText": "Open",
      "createFromScratchText": "Create empty template",
      "createFromSharedTemplateText": "Create from shared template",
      "saveText": "Save",
      "copyText": "Copy",
      "deleteText": "Delete",
      "designViewText": "Design View",
      "addTestGroupText": "Add test group",
      "deleteTestGroupText": "Delete test group",
      "statementText": "Statement",
      "okButtonText": "OK",
      "cancelButtonText": "Cancel",
      "msgSaveSuccessText": "Save Successfully",
      "msgDeleteConfirmText": "Are you sure to delete this template",
      "msgDeleteSuccessText": "Delete Successfully",
      "enableSharingText": "Share this template",
      "templateScopeTemplateText": "Template Scope",
      "publicTemplateText": "Public",
      "privateTemplateText": "Private",
    },
    "users": {
      "createUserText": "Create new user",
      "usernameText": "Username",
      "inputUsernameText": "Input username",
      "passwordText": "Password",
      "inputPasswordText": "Input password",
      "confirmPasswordText": "Confirm password",
      "inputConfirmPasswordText": "Input password again",
      "nameText": "Name",
      "inputNameText": "Input name",
      "phoneText": "Phone",
      "inputPhoneText": "Input phone",
      "roleText": "Role",
      "orgText": "Org",
      "orgUserText": "Org user",
      "orgNameText": "Org name",
      "supervisorText": "Supervisor",
      "msgInvalidUsernameError": "Invalid username (please input 3~8 characters)",
      "msgInvalidNameError": "Name field is required",
      "msgInvalidPasswordError": "Invalid password (please input 3~10 characters)",
      "msgInvalidPasswordNotMatchError": "Please confirm your password"
    },
    "forms": {
      "submitText": "Submit",
      "formText": "Form",
      "previewText": "Preview",
      "uploadAttachmentText": "Attachment",
      "saveText": "Save",
      "msgSubmitConfirm": "You won't be able to edit form after submit it, are you sure to submit it?",
      "msgAttachmentWarning": "NOTE: Each form can only bind with one attachment，attachment will be overwritten if you upload multi-times. And attachment can not be larger than 50MB",
      "chooseFileText": "Choose file",
      "viewAttachmentText": "View attachment",
      "assessmentOwnerText": "Creator",
      "submitDate": "Submit date",
      "scoreText": "Score",
      "totalScoreText": "Total score",
      "attachmentScoreText": "attachment score",
      "actionText": "Action",
      "uploadText": "Upload",
      "msgSaved": "Saved successfully",
      "msgUploaded": "Upload successfully",
      "msgFailed": "Upload failed",
      "msgChooseFile": "Please choose a file"
    },
    "profile": {
      "userInfoText": "User Info",
      "orgInfoText": "Org Info",
      "saveText": "Save",
      "nameText": "Name",
      "inputNameText": "Please input name",
      "passwordText": "Password",
      "inputPasswordText": "Please input password",
      "confirmPasswordText": "Confirm Password",
      "inputConfirmPasswordText": "Please input password again",
      "phoneText": "Phone",
      "inputPhoneText": "Please input phone",
      "orgNameText": "Org Name",
      "provinceText": "Province",
      "cityText": "City",
      "districtText": "District",
      "postcodeText": "Postcode",
      "inputOrgNameText": "Please input org name",
      "inputProvinceText": "Please input province",
      "inputCityText": "Please input city",
      "inputDistrictText": "Please input district",
      "inputPostcodeText": "Please input postcode",
      "inputAddressText": "Please input address",
      "addressText": "Address",
      "msgProfileSaved": "Profile saved",
      "msgRequireNameError": "Name can not be empty",
      "msgInvalidPasswordError":"Password is invalid(6~10 characters)",
      "msgInvalidConfirmPasswordError":"Please confirm password",
      "msgRequireOrgNameError": "Org name can not be empty"
    },
    "participants": {
      "orgNameText": "Org Name",
      "msgOrgRequiredNameError": "Org Name can not be empty",
      "provinceText": "Province",
      "cityText": "City",
      "districtText": "District",
      "postcodeText": "Postcode",
      "qualificationText": "Qualification",
      "orgTypeText": "Org Type",
      "iconText": "Org ICON (< 5MB)",
      "signatureText": "Org Signature (PNG, sz=200x200, < 5MB)",
      "userListText": "User List",
      "affiliatesText": "Affiliates",
      "addAffiliatesText": "Add Affiliates",
      "supervisorText": "Supervisor",
      "qualification1": "Level 1",
      "qualification2": "Level 2",
      "qualification3": "Level 3",
      "uploadCompleteText": "File uploaded",
      "uploadFailedText": "File upload failed",
      "deleteText": "Delete",
      "createOrgText": "Create new participant",
      "inputOrgNameText": "Input Org Name",
      "inputProvinceText": "Input province",
      "inputCityText": "Input city",
      "inputDistrictText": "Input district",
      "inputPostcodeText": "Input postcode",
      "inputAddressText": "Input address",
      "addressText": "Address",
      "inputOrgTypeText": "Input org type",
      "noAffiliatesText": "No Affiliates"
    },
    "roles": {
      "createRoleText": "Create Role",
      "moduleText": "Module",
      "functionalityText": "Functionality",
      "readText": "Read",
      "saveText": "Save",
      "addText": "Add",
      "deleteText": "Delete",
      "roleNameText": "Role Name",
      "msgRequireRoleNameError": "Role name can not be empty",
      "inputRoleNameText": "Input role name"
    },
    "categories": {
      "createCategoryText": "Create Test Category",
      "categoryNameText": "Name",
      "inputCategoryNameText": "Input category name",
      "msgRequireCategoryNameError": "Category name can not be empty"
    },
    "codeGroups": {
      "createCodeGroupText": "Create Code Group",
      "groupNameText": "Name",
      "inputGroupNameText": "Input code group name",
      "msgRequireNameError": "Code group name can not be empty"
    },
    "codes": {
      "createCodeText": "Create Code",
      "codeText": "Code",
      "codeNameText": "Code Name",
      "inputCodeText": "Input code",
      "inputCodeNameText": "Input code",
      "msgRequireCodeError": "Code can not be empty",
      "msgRequireCodeNameError": "Code name can not be empty",
      "codeGroupText": "Code Group",
      "testCategoryText": "Test Category",
      "addCategoryText": "Add Category",
      "categoryText": "Category",
      "actionText": "Action"
    },
    "assessment": {
      "msgNotAllowCreateAssessmentText": "Your account is restricted to use this functionality, contact system admin for more details",
      "msgNewAssessmentConfirmText": "PT won't be changed again, please review your settings. Are you sure to create it?",
      "msgRequireTemplateError": "You have to choose a template",
      "msgRequireAllCertFieldsError": "Please finish your certification settings",
      "msgInvalidScoreError": "Invalid qualification score",
      "msgRequireAllFields": "All fields are required",
      "msgRequireParticipantError": "Please choose at least one participant",
      "msgRequireSpecimenCodeError": "Please input specimen code",
      "assessmentNameText": "PT Name",
      "inputAssessmentNameText": "Please input name for PT",
      "templateText": "Template",
      "startDateText": "Start Date",
      "endDateText": "End Date",
      "enableCertificationText": "Enable certification",
      "qualificationScoreText": "Qualification score",
      "inputQualificationScoreText": "Input qualification score",
      "issuerText": "Issuer",
      "inputIssuerText": "Input issuer name",
      "issueDateText": "Issue Date",
      "certTitleText":"Certification Title",
      "inputCertTitleText":"Input certification title",
      "certSubTitleText":"Certification Subtitle",
      "inputCertSubTitleText":"Input certification subtitle",
      "certContentText":"Certification Content",
      "inputCertContentText":"Input certification content",
      "certCommentLabelText":"Comment Section Title",
      "inputCertCommentLabelText":"Input comment section title",
      "certCommentText":"Comment Label",
      "inputCertCommentText":"Input comment label",
      "previewCertText": "Preview",
      "selectParticipantsText": "Select participants",
      "specimenText": "Specimen",
      "inputSpecimenCodeText": "Set Code",
      "actionText": "Action",
      "okButtonText": "OK",
      "cancelButtonText": "Cancel",
      "singleSpecimenCodeText": "Single Specimen Code",
      "doubleSpecimenCodeText": "Double Specimen Code",
      "participantText": "Participant",
      "creatorText": "Creator",
      "statusText": "Status",
      "addParticipantText": "Add Participant",
      "assessmentScoreText": "PT Score",
      "additionalScoreText": "Additional Score",
      "totalScoreText": "Total Score",
      "exportText": "Export",
      "noticeText": "Notice",
      "updateText": "Edit",
      "deleteText": "Delete",
      "reopenText": "Re-open",
      "rejectText": "Reject",
      "attachmentText": "Attachment",
      "finalizeText": "Finalize",
      "statusUnknownText": "Unknown",
      "statusFinalizedText": "Finalized",
      "statusInprogressText": "In progress",
      "statusReviewedText": "Reviewed",
      "statusUnfilledText": "Open",
      "statusDraftText": "Draft",
      "statusReviewingText": "Reviewing",
      "statusPublishedText": "Published",
      "statusFilledText": "Submitted",
      "certificationText": "Certification",
      "supervisorText": "Supervisor",
      "assessmentsText": "PTs",
      "testCategoryText": "Test Category",
      "msgConfirmReset": "Are you sure re-open this PT?",
      "msgConfirmReopen": "Are you sure re-open this form?",
      "msgConfirmDelete": "Are you sure delete this form?",
      "msgConfirmDeleteAssessment": "Are you sure delete this PT and all related forms?",
      "msgOperationComplete": "Operation Complete",
      "additionScoreStatementText": "Statement",
      "inputAdditionScoreStatementText": "Input additional score statement",
      "msgConfirmFinalize": "Are you sure finalize this PT?",
      "averageText": "Average"
    }
  }
};